### ISSUE TITLE
ADVI variational inference support?

### ISSUE THREAD

**Issue by nowozin** [goedman/Stan.jl#12]
Hi,

thanks for Stan.jl, it is a great package!

As of version 2.7.0 Stan supports variational inference as well.  At the moment, is there any way to use the ADVI variational method from Stan.jl?

Thanks,
Sebastian

**Comment by goedman** [comment]
Hi Sebastian,

Thank you for your question. I will see if I can make ADVI work. I was dragging my feet a bit to see what changes the Stan team were going to make in the output format in the created .csv file.

Regards,
Rob

**Comment by goedman** [comment]
Stan 0.3.1 on Julia v0.4 now supports ADVI. An example is in the Bernoulli example subdirectory.
