### ISSUE TITLE
Test Fails

### ISSUE THREAD

**Issue by fisherc2** [goedman/Stan.jl#14]
Since updating  to Julia .4, I've encountered numerous problems. I suspect that the problems might be related to the failed package test, which gives the following error message: 

INFO: Testing Stan
Running tests for Stan-j0.3-v0.2.1:

  * test_utilities.jl *
ERROR: LoadError: could not open file /Users/chrisfisher/.julia/v0.4/Cairo/src/../deps/deps.jl
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/chrisfisher/.julia/v0.4/Cairo/src/Cairo.jl, in expression starting on line 7
ERROR: LoadError: LoadError: Failed to precompile Cairo to /Users/chrisfisher/.julia/lib/v0.4/Cairo.ji
 in error at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:383
 in require at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/chrisfisher/.julia/v0.4/Compose/src/cairo_backends.jl, in expression starting on line 4
while loading /Users/chrisfisher/.julia/v0.4/Compose/src/Compose.jl, in expression starting on line 141
ERROR: LoadError: Failed to precompile Compose to /Users/chrisfisher/.julia/lib/v0.4/Compose.ji
 in error at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:383
 in require at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/chrisfisher/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 9
ERROR: LoadError: LoadError: LoadError: LoadError: Failed to precompile Gadfly to /Users/chrisfisher/.julia/lib/v0.4/Gadfly.ji
 in error at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:383
 in require at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from /Users/chrisfisher/.julia/v0.4/Stan/test/runtests.jl:22
 in anonymous at no file:21
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/chrisfisher/.julia/v0.4/Mamba/src/Mamba.jl, in expression starting on line 6
while loading /Users/chrisfisher/.julia/v0.4/Stan/src/Stan.jl, in expression starting on line 5
while loading /Users/chrisfisher/.julia/v0.4/Stan/test/test_utilities.jl, in expression starting on line 1
while loading /Users/chrisfisher/.julia/v0.4/Stan/test/runtests.jl, in expression starting on line 20
LoadError: Stan had test errors
while loading In[9], in expression starting on line 1

 in error at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in test at pkg/entry.jl:753
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

================================[ ERROR: Stan ]=================================

failed process: Process(`/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /Users/chrisfisher/.julia/v0.4/Stan/test/runtests.jl`, ProcessExited(1)) [1]

===============================================================================

**Comment by goedman** [comment]
@fisherc2 Hi, Julia v0.4 requires Stan-0.3.1. Unfortunately I did not update the version line in Pkg.test("Stan"). I apologize for that, but that should not cause above problems, it is just confusing.

It looks like your problems are even earlier, in attempting to load Cairo, or maybe Gadfly. I suggest a couple of steps to figure out what's happening:

1. Did you recently run Pkg.update()?
2. Does "using Gadfly" and "using Cairo" and "using Mamba" all work (preferably each in a fresh version of the REPL)?
3. What is the output of Pkg.status() and versioninfo()?
4. Would you mind running: Pkg.checkout("Stan") - This will update the version line I mentioned above.
5. Try Pkg.test("Stan") again after restarting the REPL.

Can you send the outputs in REPL directly to me (goedman@icloud.com)?

Thanks and regards,
Rob

**Comment by goedman** [comment]
Problem (was actually in Gadfly, Cairo and Compose) resolved by reinstalling Julia from Julia website via the .dmg file. Since then the 'brew install julia' route has been updated and all El Capitan bottles are now available.
