### ISSUE TITLE
Install ok but had to manually install cmdstan and define CMDSTAN_HOME

### ISSUE THREAD

**Issue by robertfeldt** [goedman/Stan.jl#15]
I can install the Julia Stan package without problems now but when I try the Bernoulli example I get:

```
julia> sim1 = stan(stanmodel, bernoullidata, ProjDir, diagnostics=false, CmdStanDir=CMDSTAN_HOME);
chdir /Users/feldt/usr/local/cmdstan-2.6.0: no such file or directory (ENOENT)
```

and there is indeed no such directory. To solve this I downloaded latest cmdstan from here:

https://github.com/stan-dev/cmdstan/releases

unpacked it, ran
````
make build
```
and then in julia set the CMDSTAN_HOME variable to where I had unpacked cmdstan. After this I could successfully run the bernoulli.jl example from Stan.jl. 

Maybe updating the README to make these steps clear? Or did I miss something?

**Comment by goedman** [comment]
Hi Robert ( @robertfeldt ),

Thank you for your message. I will update the README to emphasize this better. I have experimented a bit with Pkg.build() to 'automate' the CmdStan installation but without success.

Glad it works now, please let me know if you have other feedback as I'm slowly starting to think about what a version 1.0.0 should look like.

Regards,
Rob

**Comment by robertfeldt** [comment]
Hi Rob,

Thanks for this. Maybe I should have read up more clearly before just jumping ahead, but clarifying this in the README might help people like me... :)

No major problems otherwise, looks good to me. I'll get back if I see anything major. Really happy to be able to easily interface Stan and Julia. Big thanks for your work.

**Comment by robertfeldt** [comment]
BTW, I think what fooled me is that the version list info is on top. So I never went down to find the more detailed installation instructions etc.
