### ISSUE TITLE
plot example does not work

### ISSUE THREAD

**Issue by tpapp** [goedman/Stan.jl#16]
In the README,
```julia
p = plot(sim, [:trace, :mean, :density, :autocor], legend=true);
draw(p, ncol=4, filename="summaryplot", fmt=:svg)
```
but the second line gives me an error:
```julia
julia> draw(p, ncol=4, filename="summaryplot", fmt=:svg)
ERROR: MethodError: `isless` has no method matching isless(::Float64, ::Void)
Closest candidates are:
  isless(::Float64, !Matched::Float64)
  isless(::AbstractFloat, !Matched::AbstractFloat)
  isless(::Real, !Matched::AbstractFloat)
  ...
 in max at operators.jl:57
 in apply_coordinate at /home/tamas/.julia/v0.4/Gadfly/src/coord.jl:232
 in render_prepared at /home/tamas/.julia/v0.4/Gadfly/src/Gadfly.jl:776
 in render at /home/tamas/.julia/v0.4/Gadfly/src/Gadfly.jl:722
 in draw at /home/tamas/.julia/v0.4/Mamba/src/output/plot.jl:45
```
Using 4.1, but get the same with latest nightly.
*Workaround:* dropping the `[:trace, :mean, :density, :autocor]` argument.

**Comment by goedman** [comment]
Oops, hadn't seen this issue. My apologies.

Can you tell me which versions of Stan, Mamba and Gadfly you are using? I have some difficulty reproducing this issue.

Regards,
Rob

**Comment by tpapp** [comment]
Now it works fine for me too, I guess the issue must have resolved through some update.

**Comment by goedman** [comment]
Great. Yes, Mamba (and the posterior/plot facilities I use in Stan.jl) are improving all the time.
