### ISSUE TITLE
CmdStan does not install properly with Homebrew

### ISSUE THREAD

**Issue by ahwillia** [goedman/Stan.jl#17]
I installed `cmdstan` using:

```
brew install cmdstan
```

I then added the path in `.juliarc.jl`

```julia
CMDSTAN_HOME = "/usr/local/Cellar/cmdstan/2.7.0/"
```

I believe this is the correct directory, it has `bin/`, `include/`, and `share/` directories within it. I've confirmed that the variable `CMDSTAN_HOME` is set appropriately when I launch julia.

When I either try to reproduce the example given in the README or run `Pkg.test()` I get errors like:

```
ErrorException("failed process: Process(`make /Users/alex/.julia/v0.4/Stan/Examples/Bernoulli/tmp/bernoulli`, ProcessExited(2)) [2]")
```

`Pkg.test()` also outputs this line:

```
CMDSTAN_HOME found, but CmdStan not installed properly.
```

Is there a way I can test that homebrew installed cmdstan correctly? Any other thoughts on what the problem could be? Thanks in advance. -- Alex

**Comment by goedman** [comment]
Hi Alex,

Thanks for bringing this to my attention. I’d been experimenting a bit with brew to get this to work but got nowhere (I just didn’t understand brew etc. well enough).

I’m trying it right now to see what could be the issue.

One thing I am concerned about is that is seems to be building version 2.7.0, but I’ll check that out.

Regards,
Rob

**Comment by goedman** [comment]
Hi Alex,

What gets installed on your machine? See below what I see on my machine.

I’m also worried if this will ever work without a makefile present. I’ve checked the stan compiler (2.7.0/bin/stanc), that seems to produce the bernoulli.hpp file.

But the next compilation line to link the .hpp file is quite complicated:


--- Linking C++ model ---
clang++ -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I src -I stan_2.9.0/src -isystem stan_2.9.0/lib/stan_math_2.9.0/ -isystem stan_2.9.0/lib/stan_math_2.9.0/lib/eigen_3.2.4 -isystem stan_2.9.0/lib/stan_math_2.9.0/lib/boost_1.58.0 -Wall -pipe -DEIGEN_NO_DEBUG -Wno-unused-function -Wno-tautological-compare -Wno-c++11-long-long    -O3 -o /Users/rob/.julia/v0.4/Stan/Examples/Bernoulli/tmp/bernoulli src/cmdstan/main.cpp -include /Users/rob/.julia/v0.4/Stan/Examples/Bernoulli/tmp/bernoulli.hpp 

Nevertheless I would love to get this to work but as I’m about to travel to Europe for 2 weeks this Saturday, I won’t have time to investigate until early next year.

The easiest way for you to get this up and running is likely to just use the normal make commands with Xcode installed. If you run into issues I can try to help out. 

After downloading and uncompressing the tar file, the basic steps are:

make build -j2
make examples/bernoulli/bernoulli
cd examples/bernoulli
To execute sampling of the model, use

./bernoulli sample data file=bernoulli.data.R

Regards,
Rob

--------------------------------------------------------------------

What I see on my machine:


I see after 'brew tap homebrew/science’ and ‘brew install cmdstan’, I see CMDSTAN_HOME pointing at 2.7.0:


 

When I build cmdstan I see CMDSTAN_HOME pointing at cmdstan:

**Comment by ahwillia** [comment]
What I have matches the first picture you uploaded. I'll try doing this manually as you suggest - Thanks!

**Comment by goedman** [comment]
Thanks Alex, I’ve also sent an email to Shaun about the existing home-brew formula.

Rob

**Comment by robertfeldt** [comment]
I think I have fixed the homebrew formula for cmdstan and updated to 2.9.0, at least it works on my machine. I submitted a PR to homebrew:

https://github.com/Homebrew/homebrew-science/pull/3215/files

but in the mean time you can just try to download and then install cmdstan with this formula file:

https://raw.githubusercontent.com/robertfeldt/homebrew-science/master/cmdstan.rb

I also changed to this in my juliarc.jl file and at least the Stan.jl example from the README works for me:

```
CMDSTAN_HOME = "/usr/local/Cellar/cmdstan/2.9.0"
JULIA_SVG_BROWSER = "Google Chrome.app"
```
