### ISSUE TITLE
Using "save_warmup = 1" returns only one sample

### ISSUE THREAD

**Issue by alecksphillips** [goedman/Stan.jl#20]
When sampling a model with:
```julia
model = Stanmodel(Sample(save_warmup=1),...)
sim = Stan.stan(model,data,...)
```

Only the one sample is returned in the Mamba.Chains object `sim`.

However, the model_samples.csv file has the expected number of samples (num_warmup+num_samples) in it.

I should also note that the Stan executable returns the message:
`Warning: non-fatal error reading adapation data`.

**Comment by goedman** [comment]
Hi Alex,

Will have a look.

Regards,
Rob

**Comment by goedman** [comment]
Hi Alex,

Can you try again after: Pkg.checkout(“Stan”) ?

Thanks for reporting this bug!

Regards,
Rob

**Comment by alecksphillips** [comment]
Hi Rob,

Thanks for looking into it.
It now returns only the last warmup iteration and the sampling iterations.
I've fixed that in #21
Apologies if this was the desired behavior, in which case, is there an option to obtain the warmup iterations as well?

Regards,
Alex

**Comment by goedman** [comment]
Hi Alex,

Thanks for helping out with this!

If we take the #21 approach, I expect all warmup samples take part in posterior analysis. I will check this with Brian, just to make sure.

Would it work for you if we pretty much duplicate read_stanfit_samples() as a new method, say read_stanfit_warmup_samples() that returns a Mamba chain of only the warmup samples? 

We could opt not to export that new function, but it is still available to the user as Stan.read_stanfit_warmup_samples(). Internally we could implement the bulk of this new method by adding an argument to the current read_stanfit_samples(stanmode; warmup=true). The default would be 'false', like the diagnostics argument. Is it useful to return it as a Mamba chain or would it be better to return a Julia array?

The other part, and thank you for raising that, is this inclusion of the last warmup sample and omitting the final sample. I'd forgotten about this issue.

Finally, when you say 'save_warmup=1' you talk in CmdStan terms, in Stan.jl I believe you're using 'save_warmup=true'?

Regards,
Rob

**Comment by alecksphillips** [comment]
Hi Rob,

Thanks, a read_stanfit_warmup_samples() method would suit my purposes just fine; a Mamba chain is also fine as output, I can just cat them together.

And yes, I am using 'save_warmup=true', that was just me confusing myself after poking around with Cmdstan under the hood.

Cheers,
Alex

**Comment by goedman** [comment]
Hi Alex, in the latest master I have exported the method 'read_stanfit_warmup_samples(stanmodel)' that will return just the warmup samples as a Mamba chain. The 1-off indexing should also be fixed.

For now I have exported the method as this 'export-or-not' is a broader issue.

Let me know if this works for you. Thanks again for your help.

Regards,
Rob

**Comment by alecksphillips** [comment]
Hi Rob,

It works! That's going to be a great help to me.
Thank you again.

Regards,
Alex
