### ISSUE TITLE
Does stansummary still exist?

### ISSUE THREAD

**Issue by dmbates** [goedman/Stan.jl#23]
The Julia function `stan_summary` tries to call an executable `$(CmdStanDir)/bin/stansummary` but that executable was not built in my copy of `cmdstan-2.6.0`.  Am I missing something?

**Comment by goedman** [comment]
Hi Doug, not sure what it was called previously (stanreader?), but since stan-2.8 it is now called stansummary. I think the old binary was dropped in stan-2.9.0. How hard is it for you to upgrade to 2.9.0?

**Comment by dmbates** [comment]
Thanks Rob.  I'll go ahead and upgrade.  I managed to confuse myself in that I installed cmdstan-2.9.0 on my laptop a few days ago and when I saw that I had cmdstan-2.6.0 on my desktop my faulty memory convinced me that it was the latest version.
