### ISSUE TITLE
Both Stan and Optim export Newton

### ISSUE THREAD

**Issue by robertfeldt** [goedman/Stan.jl#27]
I was comparing the results of a Bayesian SLOPE regression model with one that uses Optim for minimizing the loss function in SLOPE but ran into problems since Newton is exported by both packages. Not sure what is the best way to avoid these things but reporting it anyway since this type of comparison may not be super-uncommon... ;)

````julia
WARNING: both Optim and Stan export "Newton"; uses of it in module Main must be qualified
````

**Comment by goedman** [comment]
Not sure what the right solution would be here beyond what is suggested by the warning. I can choose not to export Newton (and several other methods). But in that case if folks don't qualify they would get an error. I've not used Optim a lot, do you have a small sample script I can use to experiment? But I'm open for suggestions what folks would prefer.

By the way did you upgrade Homebrew's cmdstan formula? Like magic it got upgraded :-). I don't think Stan.jl, CmdStan and Homebrew upgrades will always be in sync, so I will update the README to check the latest version available in the formula.

**Comment by robertfeldt** [comment]
No,  I agree, not easy to solve this. Here is an example script (it needs to be a Box minimization and use Fminbox, if not there is no warning):

````julia
using Stan, Optim
optimize(x -> sum(x), zeros(10), (-1*ones(10)), ones(10), Fminbox(), LBFGS())
`````

No, I did not update to cmdstan 2.11, seems the homebrew/science guys are evolving my recipe file as soon as there is a new cmdstan out nowadays... :)

**Comment by robertfeldt** [comment]
Actually, seems I was misunderstanding the Optim API. You can probably close this issue then. Sorry for the "fuss".

**Comment by robertfeldt** [comment]
BTW, thanks again for Stan.jl, was a breeze to get Bayesian SLOPE sparse regression up and running. Very impressive results compared to non-Bayesian SLOPE but a lot slower... ;)
