### ISSUE TITLE
Slow writing of <model>_<i>.data.R

### ISSUE THREAD

**Issue by jonalm** [goedman/Stan.jl#28]
First of all, thanks for putting this up. It is greatly appreciated.

This might be more a question than an issue, but in any case. When using the stan.jl module on input data consisting of ~200K floating point values per thread, I observe a slow down due to the writing of the data into the `<model>_<i>.data.R` files. When I manually monitor the `tmp/` directory I estimate that julia spends 1-2 minutes on writing each of these files (the files are approx 1.5 MB each and I use a 1 year old macbook pro). Is this expected behaviour? This seems really slow to me, but there might be something else going on?

**Comment by goedman** [comment]
Hi Jon, thanks for raising this issue. 

Right now I'm traveling and have no access to my computer to experiment. I'll take a look on my return next Tuesday, but after a quick review of update_R_file() I can't say I'm really surprised. Are these ~200K fp values data (i.e. fixed while your trying out different Stan models) or do you generate and/or collect these for each model run? How long in total does the sampling take?

Regards,
Rob

**Comment by jonalm** [comment]
I have to generate new data every time; my dataset is actually at the order of 10 M, and I randomly select uncorrelated subsets of ~ 200 K to make my problem tractable. I end up spending more than 50% of the running time writing data, since the sampling can run in parallel. I found the bottleneck in the code and made a pull-request see [#29].
