### ISSUE TITLE
update_R_file (in stancode.jl) fails when handling large arrays

### ISSUE THREAD

**Issue by michael-prange** [goedman/Stan.jl#31]
I'm a new user to Stan on julia, although I'm a long-time cmdstan user. I'm working on a problem where arrays of over a million elements need to be written to the .R file. I noticed that the stan() function never returned, seeming to get stuck just after opening the .R file but not writing to it. Upon investigation I found that update_R_file() puts each stan variable into a string before writing it, meaning that a large array generates a huge string. It's my guess that julia balks at this huge string. I modified update_R_file() to write arrays using writecsv() instead, and this solved the problem. My updated code is attached. I'm new to github, so pardon me if there is another way to upload proposed revisions. You'll note that the revised code is shorter as well.

Michael

function update_R_file{T<:Any}(file::String, dct::Dict{String, T}; replaceNaNs::Bool=true)
  isfile(file) && rm(file)
  strmout = open(file, "w")
  
  str = ""
  for entry in dct
    str = "\""*entry[1]*"\""*" <- "
    val = entry[2]
    if length(val)==1 && length(size(val))==0
      # Scalar
      str = str*"$(val)\n"
    elseif length(val)==1 && length(size(val))==1
      # Single element vector
      str = str*"$(val[1])\n"
    elseif length(val)>1 && length(size(val))==1
      # Vector
      str = str*"structure(c("
#= Replace this code
      for i in 1:length(val)
        str = str*"$(val[i])"
        if i < length(val)
          str = str*", "
        end
      end
=## with this code
      write(strmout, str)
      str = ""
      writecsv(strmout, val');
###
      str = str*"), .Dim=c($(length(val))))\n"
    elseif length(val)>1 && length(size(val))>1
      # Array
      str = str*"structure(c("
#= Replace this code
      for i in 1:length(val)
        str = str*"$(val[i])"
        if i < length(val)
          str = str*", "
        end
      end
=## with this code
      write(strmout, str)
      str = ""
      writecsv(strmout, val[:]');
###
      dimstr = "c"*string(size(val))
      str = str*"), .Dim=$(dimstr))\n"
    end
    write(strmout, str)
  end
  close(strmout)
end

**Comment by goedman** [comment]
Hi Michael,

Thank you for the suggestion. 

As it happens Jon Alm Eriksen did suggest another update to the update_R_file() function ( https://github.com/goedman/Stan.jl/issues/28 ). 

This update was merged yesterday and you can try it by executing Pkg.checkout("Stan") in the REPL. You could try if this helps, I'm not 100% sure. 

In the meantime I'll go over your code in more detail.

Regards,
Rob

**Comment by michael-prange** [comment]
I tried Jon's fix and found that it fails on my machine with N=10^6, which is the size I need for my work. My fix works with those values. In the following tests, Jon's fix has the _fix suffix and the original function has _old. Here are the test results for N=10^4:

N = 10000
data = Dict("Scalar" => rand(),
            "Single_element_vector" => [rand()], 
            "Vector" => rand(N),
            "Array" => rand(N,3))
@time Stan.update_R_file("testdata0", data)
@time Stan.update_R_file_fix("testdata1", data)
@time Stan.update_R_file_old("testdata2", data)

 0.048601 seconds (40.20 k allocations: 4.391 MB)
  0.057798 seconds (238.08 k allocations: 8.189 MB)
 10.872421 seconds (638.19 k allocations: 56.659 GB, 20.10% gc time)

You'll note that my fix uses many fewer allocations. Here are the results for N=10^6:

N = 1000000
data = Dict("Scalar" => rand(),
            "Single_element_vector" => [rand()], 
            "Vector" => rand(N),
            "Array" => rand(N,3))
@time Stan.update_R_file("testdata0a", data)

2.143745 seconds (4.00 M allocations: 285.998 MB, 6.16% gc time)
Note that Jon's fix crashes my kernel.

Here is my code again for completeness. I apologize for not knowing how to post this code on github. The key aspect of my fix is to replace the string concatenation with a call to writecsv() for vectors and arrays.

function update_R_file{T<:Any}(file::String, dct::Dict{String, T})
  isfile(file) && rm(file)
  strmout = open(file, "w")
  
  str = ""
  for entry in dct
    str = "\""*entry[1]*"\""*" <- "
    val = entry[2]
    if length(val)==1 && length(size(val))==0
      # Scalar
      str = str*"$(val)\n"
    elseif length(val)==1 && length(size(val))==1
      # Single element vector
      str = str*"$(val[1])\n"
    elseif length(val)>1 && length(size(val))==1
      # Vector
      str = str*"structure(c("
      write(strmout, str)
      writecsv(strmout, val')
      str = "), .Dim=c($(length(val))))\n"
    elseif length(val)>1 && length(size(val))>1
      # Array
      str = str*"structure(c("
      write(strmout, str)
      writecsv(strmout, val[:]')
      dimstr = "c"*string(size(val))
      str = "), .Dim=$(dimstr))\n"
    end
    write(strmout, str)
  end
  close(strmout)
end

**Comment by goedman** [comment]
@michael-prange 

Thanks for the additional testing. I have merged your suggested change and added a test_csv.jl in the test directory to compare the timings.

 @jonalm,

In the master version of stan code.jl I have renamed your version to update_R_file_jon() and removed the '_old' version. Some testing on my side confirms @michael-prange 's conclusions (about equally fast and can handle N = 10^7. Can you live with this further update?

Regards,
Rob

**Comment by jonalm** [comment]
Ha! I just ran into the same problem. @michael-prange 's solution is obviously much better than mine. `writecsv` should be optimised for writing numbers to text with commas in between. Thanks for fixing this.

@goedman, you can just remove the update_R_file_jon() version. Thanks again for the quick update.

Best,
Jon

**Comment by goedman** [comment]
Done. Thank you both!
