### ISSUE TITLE
update_R_file exports single element vector as scalar, causing error

### ISSUE THREAD

**Issue by marcocox** [goedman/Stan.jl#34]
Data vectors containing a single element get written to the R input data file like a scalar, according to https://github.com/goedman/Stan.jl/blob/master/src/stancode.jl#L182.
This causes a dimensionality error if I have just one data point:

```
std::exception::what: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=y; dims declared=(1); dims found=()
```

Simpy removing the special treatment of single element vectors would solve this. Is there a reason for not doing this? Thanks!

**Comment by goedman** [comment]
Hi Marco,

Thanks for spotting this!

No, at least I don't remember why this was needed when I wrote update_R_file(). Can you make a PR?

Or can you confirm that your testing shows combining the first 2 if/elseif is what fixes it?

Or a simple test example that I can add to run tests.

Regards,
Rob

**Comment by marcocox** [comment]
Hi Rob,

Thanks for your quick reply! I just posted PR #35, which adds a test and fixes the issue.

Regards, Marco

**Comment by goedman** [comment]
Hi Marco,

Today I'm traveling (at least this morning), will merge later today or tomorrow.

I will likely make it a separate example/test case.

Thanks for your help,
regards, 
Rob

**Comment by marcocox** [comment]
Great, thanks Rob!

**Comment by goedman** [comment]
Hi Marco, done. Cab you let me know if this doesn't fix the issue? It should I guess. I'll close this issue for now. Thank for your help!

**Comment by marcocox** [comment]
Hi Rob, yes it works as expected, thanks a lot!
