### ISSUE TITLE
TypeError for user defined starting points

### ISSUE THREAD

**Issue by fisherc2** [goedman/Stan.jl#38]
I am trying to initialize the starting values for my model.  As an example, I  tried to run BernoulliInitTheta. However, I received the following error:

> TypeError: typeassert: expected Number, got Array{Dict{String,Any},1}
>  in (::Core.#kw#Type)(::Array{Any,1}, ::Type{Stan.Init}) at <missing>:0
>  in include_string(::String, ::String) at loading.jl:441
>  in include_string(::String, ::String) at sys.dylib:?
>  in eval(::Module, ::Any) at boot.jl:234
>  in eval(::Module, ::Any) at sys.dylib:?
>  in (::Atom.##65#68)() at eval.jl:40
>  in withpath(::Atom.##65#68, ::Void) at utils.jl:30
>  in withpath(::Function, ::Void) at eval.jl:46
>  in macro expansion at eval.jl:109 [inlined]
>  in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60

Any help would be greatly appreciated.

**Comment by goedman** [comment]
Hi, could you check if you are using the latest master, i.e. Pkg.checkout("Stan")? It should be on v"1.0.2+".

[BernoulliInittheta.txt](https://github.com/goedman/Stan.jl/files/804827/BernoulliInittheta.txt)

**Comment by fisherc2** [comment]
Thanks Rob. You will have to forgive my ignorance. I did not realize that github showed the most recent changes by default (as opposed to the recent stable release). It looks like its working. Thanks again.

**Comment by goedman** [comment]
No apologies needed, it’s just that tagging a new version is typically bothersome (at least without write access to Metadata). I’ve been postponing that until I can test it on Julia v”0.6”.

Regards,
Rob

**Comment by fisherc2** [comment]
Hi Again Rob-

I think I may have encountered an issue with the initialization. I receive the error message:

> Initialization from source failed.
> Initialization from source failed.
> variable mu_div_ability missing
> variable mu_div_ability missing

However, when I examine the dictionary I get:

> init[1]["mu_div_ability"]
> 0.0

Do you have any idea what would cause this error?

**Comment by goedman** [comment]
I'll try if I can reproduce this error, probably tomorrow. Is this message from CmdStan? Does the R init file look ok (in /temp)?

**Comment by fisherc2** [comment]
As far as I can tell, the R init file looks right. For that parameter in particular it reads:

> "mu_div_ability" <- 0.0

I can email my code if that helps you diagnose the problem.

Thanks.

**Comment by goedman** [comment]
That would definitely help. Thanks.

**Comment by fisherc2** [comment]
Fixed. See [Stan Issue ](https://github.com/stan-dev/stan/issues/2237#issuecomment-283178059)
