### ISSUE TITLE
Future of Stan.jl

### ISSUE THREAD

**Issue by goedman** [goedman/Stan.jl#40]
Hi,

In issue #39 I started a discussion on the future of Stan.jl by asking several questions. Hiding the discussion inside another issue is not right, so I'm moving it to its own issue.

Before tagging Stan.jl v"1.1.0" I have 3 items on my list of things to do:

1. Julia v"0.6" (also depends on Mamba and Gadfly)
2. Running Stan models from anywhere (I'm not sure why occasionally I see problems with that)
3. Fixing the initialization issues (e.g. items #34, #38 and now #39)

With respect to 3 I'm leaning towards adding a new (multiple dispatch or keyword?) argument to stan() to make this work similar to data, e.g.  ```sim1 = stan(stanmodel, bernoullidata, bernoulliinit)``` in the BernoulliInitTheta example.

Other questions (and also based on Michael's response in #39 for item 5):

4. Has anyone used item #36 (PSIS/LOO)?
5. Separating out running CmdStan and creating Mamba chains
6. Using DataTables to store and query the sampling results
7. Switch/add an option for plots using Plots.jl
8. Tracking of R functionality

I asked folks for feedback on these and other topics such as "do folks like the coupling with Mamba diagnostics and Mamba graphics?" and "how important is access to Stan functions on C++ level?".

Over the last year I have certainly seen more R focus in the Stan team, how important is that? Hence item 8 and possibly  item 4.

After 2 years is it time to do major surgery on Stan.jl? I'm also pretty busy right now, so no promises, even if I could tackle some of the larger topics.

Regards,
Rob

**Comment by chriselrod** [comment]
rstan offers log prob methods, like unconstrain_pars.
The function optimizing also has the optional hessian argument, allowing you to extract it following an optimization. These two features have me considering switching from Julia back to R.

Although I'd probably stick to Julia and write functions to do the change of variables to the unconstrained space and to calculate the log likelihood as a function of these unconstrained parameters, and then use ForwardDiff to find the hessian.
This would be less convenient (especially when applied to more models over time) vs simply using Stan.

**Comment by goedman** [comment]
Thanks for your feedback @chriselrod . My guess is that tracking RStan functionality means C++ level integration.

**Comment by fisherc2** [comment]
Hi Rob-

For what its worth, I think adding LOO would be a nice feature for model comparison. It seems like this could have been programmed in Stan so that other programs could interface with it. But it is what it is.  Tracking some of the R functionality would be beneficial too. R has certain features like expose stan functions which is handy for testing functions. Plots.jl seems like a promising option. My main complaint with Gadfly is that there does not appear to be a way to modify Mamba's default aesthetics or load pictures directly into an IDE, like Juno. 

-Chris

**Comment by goedman** [comment]
Thanks Chris.

Have you looked at [#36](https://github.com/goedman/Stan.jl/issues/36) (PSIS/LOO)?

My next step will likely be to implement item 5 above. This will allow me to port (and test) to newer versions of Julia (item 1) much earlier. Just need to find some time :-)

Rob

**Comment by fisherc2** [comment]
Rob, I did see that. Do you know if alvaro1101 plans to port that into Julia, or is that something you plan to do?

**Comment by goedman** [comment]
My understanding is that @alvaro1101 ported important parts of Aki’s matlab code to Julia (https://github.com/avehtari/PSIS/issues/3). Unfortunately I have not really had the time to study and test it. But I think it is useful work and I would love for it to be published.

Regards,
Rob

**Comment by fisherc2** [comment]
Thanks for clarifying. I was going to offer to look at the code and try to port it into Julia, but it looks like that is covered.

**Comment by goedman** [comment]
Would you mind checking with @alvaro1101 ? It would be really nice to get the package in METADATA.

**Comment by goedman** [comment]
Summarizing:

Updates for Stan.jl v"1.0.3" are listed in the README file in the current master. Thanks to a lot of help!
It will run on Julia v"0.6". 

For Stan.jl v"2.0.0" I'm planning to make the following changes (late this year):

1. Separating out running CmdStan and creating Mamba chains.
1. Only have dependencies on Mamba and Gadfly in current examples.

and maybe:

1. A Plots.jl example.
1. By default moving thinning to CmdStan (as recently suggested for Jags.jl).
1. Using DataTables to store and query the sampling results.

It's a major level change because it will effect all current examples and likely many user programs as well. I might sync the release with Julia v"1.0" if that is realistic.

**Comment by goedman** [comment]
Progress as of 5/4/2017: Items 1) and 2) in the first list completed and pass testing on both Julia 0.5 and 0.6. Next up: 2) and 5) from the second list.

**Comment by goedman** [comment]
Progress as of 5/12/2017: 2) and 5) are mostly done. I've renamed the Github branch to Stan.jl.1.1.0.

Still to do: Simplify/unify observed data and initialization data handling in stan() and improve on pinpointing where an error might occur in stan(). I'm hoping to finish this work by the end of next week and tag/release Stan.jl v"1.1.0".

**Comment by goedman** [comment]
Please also note Tamas' comments in #44 .
