### ISSUE TITLE
Failed Process

### ISSUE THREAD

**Issue by rlecover007** [goedman/Stan.jl#41]
I've been trying to determine the cause of an error message:
ErrorException("failed processes:\n  Process(`./odePlatelets sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=2 id=1 data file=odePlatelets_1.data.R output file=odePlatelets_samples_1.csv diagnostic_file=odePlatelets_diagnostics_1.csv refresh=100`, ProcessExited(70)) [70]\

 What does the 70 represent?

**Comment by goedman** [comment]
Hi @rlecover007 

I'm not sure what the code indicates. To figure out what might be happening the best thing is to have a failing example. If that is not possible, some info we should gather is:

What's your Stanmodel when calling stan(...). Does the model compile? Is there more output? What system are you on? What versions of Julia and Stan.jl (master?). Does Pkg.test("Stan") work on your system?

Regards,
Rob

**Comment by rlecover007** [comment]
Rob,

Yes, the model compiles when used with pure cmdStan. I've attached the model code. 

I am on Ubuntu 16.04, using Julia 0.5.0, Stan  1.0.2. Pkg.test("Stan") does work fine on my system.
[PlateletsStan.txt](https://github.com/goedman/Stan.jl/files/899992/PlateletsStan.txt)

**Comment by goedman** [comment]
I noticed at the bottom of the ...run.log these messages:

variable does not exist; processing stage=data initialization; variable name=theta; base type=double
variable does not exist; processing stage=data initialization; variable name=theta; base type=double
variable does not exist; processing stage=data initialization; variable name=theta; base type=double

theta is not part of the initialization data?

**Comment by rlecover007** [comment]
It's the parameters that are to be estimated.

**Comment by goedman** [comment]
Not sure if I can be of much help. I've never worked with the ode capabilities in CmdStan. It's clear that no samples are being returned by CmdStan. Maybe the Stan team can help here?

**Comment by rlecover007** [comment]
I will reach out to them. Thank you for your time and assistance.
