### ISSUE TITLE
Possible problem with initializing chain

### ISSUE THREAD

**Issue by fisherc2** [goedman/Stan.jl#43]
Hi Rob-
I think there is an issue initializing chains. When I print theta in your simple example, it prints the correct value. However, in my hierarchical example, print(omega); should yield  3, but produces a random value. I could not find an error with my code unfortunately. 

Best regards,

Chris

**Comment by goedman** [comment]
Hi Chris, where in BernoulliChris do you insert "print(omega"). It seems to me the whole output is varying quite a bit each run. Where do you insert the print(omega) statement? Yje init files look ok to me.

Regards,
Rob

**Comment by fisherc2** [comment]
In both cases, I placed the print statement immediately after the sample statement, like so:
```
model {
  omega ~ gamma(2,3);
  print("omega");
  print(omega);
  kappa ~ beta(7,3);
  theta ~ beta(A,B);
  for (obs in 1:Nobs){
    y[obs] ~ bernoulli(theta[SubjIdx[obs]]);
  }
}

```
I received the following output: 

```
omega
1.24038

omega
0.744449
...
```
However, the dictionary contained omega => 3 for both chains. So I expected the first print out to be 3.  Again, the simple example you created works. So it appears that the code may not generalize correctly.

**Comment by fisherc2** [comment]
Just for completeness, here are snippets from the working code. 

```
  bernoullimodel = "
  data { 
    int<lower=1> N; 
    int<lower=0,upper=1> y[N];
  } 
  parameters {
    real<lower=0,upper=1> theta;
  } 
  model {
    theta ~ beta(1,1);
    print(theta);
    y ~ bernoulli(theta);
  }
  "

  bernoullidata = [
    Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1]),
  ]

  bernoulliinit = Dict{String, Any}[
    Dict("theta" => 0.321321),
  ]

```
and the corresponding output:


```
0.321321

0.321321


Gradient evaluation took 1.5e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.15 seconds.
Adjust your expectations accordingly!


WARNING: No variance estimation is
         performed for num_warmup < 20

0.321321

0.477479

```
As you can see, it prints out the correct initial value (Although I'm not sure why it prints multiple times).

**Comment by goedman** [comment]
I don't know how and where these print statements exactly get folded into the generated C++ program. Above is a part of the very early part of the run.log file with 2 chains, still during warm-up?

In your example omega is 1 of 12 parameters vs. in the simple model there is just 1 (theta). I've never studied NUTS in enough detail to understand all ins and outs, but in Gibbs sampling one draws a new value given the most recent drawn values of the other parameters. Could that maybe explain what we're seeing?

**Comment by fisherc2** [comment]
I set nchains = 1 in the simple Bernoulli example. So its unclear to my why it prints .321321 multiple times. It appears to begin in the warmup phase.

Thats a good question. My naive guess is that the algorithm should use all of the initial values on the first iteration, then select new values on subsequent iterations. However, that does not seem to be the case for some reason.


For some reason, omega prints out correctly now, but not the others.
Initial values:

`init = Dict{String, Any}[Dict("kappa"=>.70000,"theta[1]"=>.60000,"theta[2]"=>.50000,"omega"=>3.0000)]
`

Model snippet

```
model {
  omega ~ gamma(2,3);
  kappa ~ beta(7,3);
  theta ~ beta(A,B);
  print("omega");
  print(omega);
  print("kappa");
  print(kappa);
  print("theta[1]");
  print(theta[1]);
  print("theta[2]");
  print(theta[2]);
  for (obs in 1:Nobs){
    y[obs] ~ bernoulli(theta[SubjIdx[obs]]);
  }
}
```
output: 


```
omega
3
kappa
0.268878
theta[1]
0.442806
theta[2]
0.432959

omega
3
kappa
0.268878
theta[1]
0.442806
theta[2]
0.432959


Gradient evaluation took 3.9e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.39 seconds.
Adjust your expectations accordingly!


WARNING: The initial buffer, adaptation window, and terminal buffer
         overflow the total number of warmup iterations.
         Defaulting to a 15%/75%/10% partition,
           init_buffer = 3
           adapt_window = 15
           term_buffer = 2

omega
3
kappa
0.268878
theta[1]
0.442806
theta[2]
0.432959

omega
0.0569474
kappa
0.907729
theta[1]
0.92227
theta[2]
0.925455

omega
3
kappa
0.268878
theta[1]
0.442806
theta[2]
0.432959

```

The other initial values were not any where in the output. So perhaps as you said, it might only initialize at one value, which appears to be the first one listed in the init.r file. That does not seem very helpful if that is true. 


I also found a [Stan issue](https://github.com/stan-dev/stan/issues/1757) about initial values. The second comment states that Stan does not print the initial values. But it is a little ambiguous to me because in the example, the values aren't obtained through print statements, but rather rstan. But I suppose its possible that it suppresses than initial printing, and what we see is one parameter fixed while the others are changing.

**Comment by goedman** [comment]
The other factor I'm not sure about is if scaling is taken care of in these print statements. 

In above example, with
```
init = Dict{String, Any}[Dict("kappa"=>.70000,"theta[1]"=>.60000,"theta[2]"=>.50000,"omega"=>3.0000)]
```
does omega ends up to be the first in the init file and did you change it since your earlier runs?

But I agree, if only one of the init values is used, initing the others is not very helpful. In MH there is also the notion of blockwise sampling. Again, not sure if that is true in NUTS.

Guess only the Stan team can confirm our suspicions.

**Comment by fisherc2** [comment]
Yeah. It ends up being the first parameter listed in the init.r files even when I had more chains (if thats what you are asking). 

Yeah. I did change the example slightly from earlier to have more control over the initial values (before they were randomly selected). 

I'll ask how the initial values work in Stan and report back. Thanks for your help.

**Comment by fisherc2** [comment]
Hi Rob-

It [turns out](https://groups.google.com/forum/#!category-topic/stan-users/general/dILGVTtLBag) that initial parameters do not print out because they are part of a leapfrog process that is different from the NUTS process. So the code is working or at least its consistent with the expected print behavior of Stan. Sorry for the false alarm!

**Comment by goedman** [comment]
Thanks for the update Chris. Each time we learn something!
