### ISSUE TITLE
could not build on Linux

### ISSUE THREAD

**Issue by tpapp** [goedman/Stan.jl#44]
```julia
julia> isfile(joinpath(ENV["CMDSTAN_HOME"], "bin/stanc"))
true

julia> VERSION
v"0.6.0-pre.beta.460"

julia> Pkg.build("Stan")
INFO: Building Rmath
INFO: Building Cairo
INFO: Building Stan
============================================================================[ ERROR: Stan ]============================================================================

LoadError: ArgumentError: Module Homebrew not found in current path.
Run `Pkg.add("Homebrew")` to install the Homebrew package.
while loading /home/tamas/.julia/v0.6/Stan/deps/build.jl, in expression starting on line 1

=======================================================================================================================================================================

===========================================================================[ BUILD ERRORS ]============================================================================

WARNING: Stan had build errors.

 - packages with build errors remain installed in /home/tamas/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Stan")`
 - build a single package by running its `deps/build.jl` script

=======================================================================================================================================================================

```
Same happens on `v0.5`. `Homebrew.jl` does not seem to support Linux. Can `Stan.jl` be used on Linux?

**Comment by goedman** [comment]
Hi @tpapp , Stan.jl on Julia v"0.6" won't work yet, currently Stan.jl requires both Mamba and Gadfly and neither is yet released for 0.6. 

The latest *master* version of Stan.jl should work on Julia v"0.5". The latest tagged version (v"1.0.2") unfortunately does not have the correct protection to prevent calling Homebrew. I apologize for that.

All of this is part of my thinking about the future of Stan.jl ( #40 ).

Regards,
Rob

**Comment by goedman** [comment]
Hi @tpapp ,

Branch Stan.jl.2.0.0 now works on Julia 6.0-. Of course it can't use Gadfly graphics nor Mamba Chains for now. But it might help with testing StanDump.jl (which I would love to use when done!).

**Comment by goedman** [comment]
Tamas ( @tpapp ), currently Stan.jl is under my name on Github but I'm wondering if it wouldn't be better to create a Github organization (JuliaStan?) that can hold multiple packages and is owned by multiple contributors. It could be the entry point for Stan in Julia packages like Stan.jl, StanDump, PSIS.
Ideally it would be JuliaMCMC with suborgs Klara, Mamba and Stan and possibly others but I don't think Github organizations support multiple levels.

If you agree, would you be willing to contribute to this organization and maybe e.g. review/mentor the quality of Stan.jl and other required packages as Stan itself is creating more and more functionality in R?

I'm still hoping to get Stan.jl v"1.1.0" (currently named branch 2.0.0) out by the end of next week based on #40 , but Stan.jl v"2.0.0" could become a much better quality Stan.jl

Regards,
Rob

**Comment by tpapp** [comment]
Rob, I am currently working on a set of packages that would help me with my Stan workflow. [StanDump.jl](https://github.com/tpapp/StanDump.jl) writes data in R's dump format, [StanRun.jl](https://github.com/tpapp/StanRun.jl) takes care of compiling and running Stan (and is probably the least robust at the moment), while [StanSamples.jl](https://github.com/tpapp/StanSamples.jl) reads samples from the CSV file, taking care to reconstitute containes, ie columns `a.1.1, a.2.1, ...` would be read as a vector of matrices, for example. This is important for me for posterior predictive checks.

These packages provide a subset of the functionality of `Stan.jl`. You may be wondering why I chose to write something independently instead of contributing to `Stan.jl`. There are three reasons for this:

1. I prefer a more modular approach, with fewer OS- and environment-specific dependencies, or at least the option of containing them in a single module (hence `StanRun.jl`),
2. I wanted to experiment with some approaches, so what I am doing will be in flux for a while, until I find the right API for my workflow,
3. at the same time, I want to maintain 90%+ test coverage for my code.

I am probably completing `StanSamples.jl` today, and will start using it for a while. In a few months, I will see what works best for me, probably refactor `StanRun.jl`, and then we may be able to work towards a unified ecosystem.

As for MCMC in Julia, I think what I miss the most is a unified framework for dealing with posterior draws. I would find it ideal if one could have a single format, which Stan libraries, Klara, Mamba, and others could read into, perform diagnostics and posterior predictive checks. This is probably what I will be working on in the next few weeks. I will announce a preliminary draft and will ask you to comment on it.

**Comment by tpapp** [comment]
Rob, I am currently working on a set of packages that would help me with my Stan workflow. [StanDump.jl](https://github.com/tpapp/StanDump.jl) writes data in R's dump format, [StanRun.jl](https://github.com/tpapp/StanRun.jl) takes care of compiling and running Stan (and is probably the least robust at the moment), while [StanSamples.jl](https://github.com/tpapp/StanSamples.jl) reads samples from the CSV file, taking care to reconstitute containes, ie columns `a.1.1, a.2.1, ...` would be read as a vector of matrices, for example. This is important for me for posterior predictive checks.

These packages provide a subset of the functionality of `Stan.jl`. You may be wondering why I chose to write something independently instead of contributing to `Stan.jl`. There are three reasons for this:

1. I prefer a more modular approach, with fewer OS- and environment-specific dependencies, or at least the option of containing them in a single module (hence `StanRun.jl`),
2. I wanted to experiment with some approaches, so what I am doing will be in flux for a while, until I find the right API for my workflow,
3. at the same time, I want to maintain 90%+ test coverage for my code.

I am probably completing `StanSamples.jl` today, and will start using it for a while. In a few months, I will see what works best for me, probably refactor `StanRun.jl`, and then we may be able to work towards a unified ecosystem.

As for MCMC in Julia, I think what I miss the most is a unified framework for dealing with posterior draws. I would find it ideal if one could have a single format, which Stan libraries, Klara, Mamba, and others could read into, perform diagnostics and posterior predictive checks. This is probably what I will be working on in the next few weeks. I will announce a preliminary draft and will ask you to comment on it.

**Comment by goedman** [comment]
Tamas, your comments are spot on and exactly what's needed for a next gen, high quality Julia CmdStan interface! If you don't mind I will continue to 'lurk in the background' and follow your work for my own education. And occasionally 'steal' your secrets, like installing CmdStan on Travis. A big step forwards!

Ultimately your last paragraph is key. It helps me immediately with making a decision for Stan.jl v"1.1.0" on several items in #40:

1. Using DataTables to store and query the sampling results
2. Switch/add an option for plots using Plots.jl in addition to Mamba graphics
3. Tracking of R functionality
4. Creation of JuliaStan Github organization

For these I think we should wait on the unified framework.

I will tag and release Stan.jl v"1.1.0" in the next 2 weeks.

**Comment by goedman** [comment]
@tpapp 

Hi Tamas,

Apologies for this direct ping. Just wanted to point you to this discussion: https://github.com/JuliaDiffEq/DiffEqBayes.jl/issues/11 .

Not sure if you are interested and/or are already following it, but just thought your ideas and insights would help here.

Regards,
Rob
