### ISSUE TITLE
Walk through example doesn't work

### ISSUE THREAD

**Issue by fredRos** [goedman/Stan.jl#45]
When running the example, stan complains

```
sim1 = Stan.stan(m, data)
...
Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int
Diagnostic information: 
Dynamic exception type: std::runtime_error
std::exception::what: variable does not exist; processing stage=data initialization; variable name=N; base type=int

ErrorException("failed processes:\n  Process(`./lin.reg sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=2 output file=lin.reg_samples_1.csv refresh=100`, ProcessExited(255)) [255]\n  Process(`./lin.reg sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=2 output file=lin.reg_samples_2.csv refresh=100`, ProcessExited(255)) [255]\n  Process(`./lin.reg sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=2 output file=lin.reg_samples_3.csv refresh=100`, ProcessExited(255)) [255]\n  Process(`./lin.reg sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=2 output file=lin.reg_samples_4.csv refresh=100`, ProcessExited(255)) [255]")
```

I hit this problem with my own code and the same problem. It is due to the fact that the `data` are just one dictionary and not a vector of dictionaries. It works if I do `Stan.stan(m, [data,data, data,data]) for the default 4 chains. That shouldn't be necessary and there is code in `src/stancode.jl` to deal with it but obviously that fails. There is no `data file=XXX.R` in the call to cmdstan. I know I updated the readme and it worked then but it doesn't anymore. Would be good to check this behavior in the tests. The bernoulli example now has different data input for every chain.

**Comment by goedman** [comment]
Hi Frederik ( @fredRos ),

Does it work if you do Stan.stan(m, [data]) ?

I fully agree with you that the observation and initialization data handling in Stan.jl is a mess.

Right now I'm making very substantial changes to Stan.jl, partially for Julia 0.6 but also to generate better documentation, optionally decouple the Mamba requirement ( at least for testing purposes),
and several other items. See #40 . I'm hoping to finish the docs this week and then look at the mapping from Julia data to R data files and the error handling in Stan.jl (which also sucks).

Are you ok for now with your work around?

Rob

**Comment by fredRos** [comment]
On 11.05.2017 16:49, Rob J Goedman wrote:
>
> Hi Frederik ( @fredRos <https://github.com/fredros> ),
>
> Does it work if you do Stan.stan(m, [data]) ?
>
> I fully agree with you that the observation and initialization data
> handling in Stan.jl is a mess.
>
> Right now I'm making very substantial changes to Stan.jl, partially
> for Julia 0.6 but also to generate better documentation, optionally
> decouple the Mamba requirement ( at least for testing purposes),
> and several other items. See #40
> <https://github.com/goedman/Stan.jl/issues/40> . I'm hoping to finish
> the docs this week and then look at the mapping from Julia data to R
> data files and the error handling in Stan.jl (which also sucks).
>
> Are you ok for now with your work around?
>
I'm ok for now, it's just that the error message didn't hint at what was
wrong so it took me a while to figure out.
Thanks for the honest reply. In my opinion the graphical output via
mamba is very useful, so I personally don't worry about that dependency.
But if it works with Plots.jl, that's fine too. I looked at shinystan.
Did you ever try to call it from julia? That seems like the best match
for stan output. I know there is a way to call R from julia but I have
no experience with R

Now I know how to run simple tests and I can check more features of stan
and Stan.jl
