### ISSUE TITLE
Stan.jl warning

### ISSUE THREAD

**Issue by goedman** [goedman/Stan.jl#47]
From Eric Chameroy on Discourse:

Hi everyone,

When I load Stan.jl, I receive the following message:
WARNING: using Stan.CMDSTAN_HOME in module Main conflicts with an existing identifier.

I had created a .juliarc.jl file containing the statement:
CMDSTAN_HOME = “C:\Users\USERNAME\CmdStan” (I’m using Windows 10)
as stated in the Stan.jl documentation for setting up CmdStan.

What does this warning mean and is there a way to fix it? Considering it’s a warning and not an error, do I need to be concerned with it at all?

**Comment by goedman** [comment]
From Robin Deits on Discourse:

Looking at the Stan.jl source code, I think this probably isn’t something you need to worry about. But I think you can make the error go away by setting an environment variable rather than creating a global Julia variable. That would mean changing your .juliarc.jl command to:

ENV["CMDSTAN_HOME"] = "C:\Users\USERNAME\CmdStan"
does that work? And does it get rid of the warning?

BTW, the relevant lines are here: https://github.com/goedman/Stan.jl/blob/ef6b07f43f575cad5b8d40e0953e013ab7def64c/src/Stan.jl#L12

**Comment by goedman** [comment]
From Rob Goedman on Discourse:

Thanks for jumping in Robin!

Hi Eric,

We’ve gone through several iterations on how to set this up in such a way that it works across platforms. Clearly it still isn’t correct.

Before changing anything, let’s see if Robin’s suggestion works. If so, maybe I should just update the documentation.

Does Pkg.test(“Stan”) work ok for you?

Regards,
Rob

**Comment by goedman** [comment]
From Eric on Discourse:

Thanks for the help!

Robin - you’re suggestion did remove the warning message, thanks.

Rob - I got errors when I ran Pkg.test(“Stan”). When that command is executed, is it running the same model as used in the walkthrough example provided in the documentation? I was trying to run that code in a Jupyter notebook and was receiving errors - I think the same as I had gotten with Pkg.test(“Stan”).

I can post the output files if that would help.

**Comment by goedman** [comment]
From Rob on Discourse:

Hi Eric,

would it be possible to switch to https://github.com/goedman/Stan.jl/issues/47 ? I have copied the thread so far.

Yes, I definitely need to see the error messages and versions you are using (I assuming Julia 0.6 and Stan.jl 2.0.0).

The first step is to see if CmdStan works.

Regards,
Rob

**Comment by chameroy** [comment]
Hi Rob,

Here are the output files. If you need anything else, let me know.

I am using Julia 0.6 and Stan.jl 2.0.0.

[bernoulli.exe_build.log.txt](https://github.com/goedman/Stan.jl/files/1216058/bernoulli.exe_build.log.txt)
[bernoulli.stan.txt](https://github.com/goedman/Stan.jl/files/1216059/bernoulli.stan.txt)

Best,
Eric

**Comment by goedman** [comment]
This looks like CmdStan is not installed properly and it attempts to install/build it. Have you been able to follow the installation instructions from the Stan website, i.e. where the Stan compiler (stand) and some other utilities are build?

We need to get to the point where we can run Bernoulli just using CmdStan.

**Comment by chameroy** [comment]
I believe I followed the instructions correctly. I created my .juliarc.jl file specifically to point to the location of CmdStan. I followed step 1.2 because I'm using Windows. Step 1.1 is for Linux/OS X, correct?

**Comment by goedman** [comment]
Hi Eric,

I’m talking about http://mc-stan.org/users/interfaces/cmdstan.html <http://mc-stan.org/users/interfaces/cmdstan.html>, particularly appendix B.3.

We need to get bernoulli.exe sample data file=bernoulli.data.R  (on page 10 of that manual) running.

Is that running on your system?

Best,
Rob

**Comment by chameroy** [comment]
Hi Rob,

Sorry, I did not have CmdStan properly set up. Thank you for pointing me to the proper documentation. I do believe CmdStan is running correctly now. Thanks for your patience. I feel somewhat silly for not having figured that out on my own.

However, I still get errors when running Pkg.test("Stan") and executing the code in a notebook, although, now the errors are different then before.

Here are the output files.
CmdStan:
[bernoulli.data.R.txt](https://github.com/goedman/Stan.jl/files/1218935/bernoulli.data.R.txt)
[bernoulli.stan.txt](https://github.com/goedman/Stan.jl/files/1218936/bernoulli.stan.txt)

Notebook output:
[bernoulli.exe_build.log.txt](https://github.com/goedman/Stan.jl/files/1218941/bernoulli.exe_build.log.txt)
[bernoulli_run.log.txt](https://github.com/goedman/Stan.jl/files/1218944/bernoulli_run.log.txt)
[bernoulli.stan.txt](https://github.com/goedman/Stan.jl/files/1218950/bernoulli.stan.txt)
[bernoulli_1.data.R.txt](https://github.com/goedman/Stan.jl/files/1218952/bernoulli_1.data.R.txt)

I would send you output files from Pkg.test("Stan"), but I don't know where to find them. I apologize if I'm uploading too many files - I'm not sure if you need anything other than the logs.

Best,
Eric

**Comment by goedman** [comment]
Hi Eric,

That looks a lot better!

Can you run your example in the REPL? Or one of the examples in Stan.jl?

Or Pkg.test(“Stan”) in REPL should display error messages that you can copy to a file.

Rob

**Comment by chameroy** [comment]
Sure. I didn't know I could just copy and paste from the REPL. Here is the Pkg.test("Stan") output:
[PkgtestStanREPL.txt](https://github.com/goedman/Stan.jl/files/1219196/PkgtestStanREPL.txt)

Eric

**Comment by goedman** [comment]
Aah, this looks like a very old issue (closed issue #9) that was brought up in 2014 (but for some reason I closed it, probably because I had no way to test).

But the error message definitely points to where I try to delete the tmp directory. Apparently I can't do that in Windows.

One quick test would be to copy and paste all text in the Examples/NoMamba/Bernoulli/bernoulli.jl file into the REPL and press return.

**Comment by chameroy** [comment]
I tried running the code in the REPL. Here's the end result:
[bernoulli_example_REPL.txt](https://github.com/goedman/Stan.jl/files/1219261/bernoulli_example_REPL.txt)

I also wasn't having any luck using the "ProjDir=" argument. At first I tried "ProjDir=pwd()", but got an error. When I dropped the "ProjDir=" part and just used "pwd()", I had a little better success. Here's the notebook file I was using to better illustrate what I'm talking about:
[Stan Example.zip](https://github.com/goedman/Stan.jl/files/1219265/Stan.Example.zip)

Eric

**Comment by goedman** [comment]
Looking through the notebook, we’re pretty close in fact. CmdStan ran fine (rc=0, Mamba chain object looks fine)

Can you remove the first line after if rc=0 (i.e. sim1 = …) and try the notebook again?

Best,
Rob

**Comment by chameroy** [comment]
No errors.

**Comment by goedman** [comment]
Yip, the call to stan(…) returns a Tuple: (rc, Mamba.Chain object).

For the filtering you just need the Mamba.Chain object.

It does bother me that I can’t remove the tmp dir using a run command and also that @__FILE__ does not work on Windows.

Rob

**Comment by goedman** [comment]
A few more remarks:

1. The ```@__FILE__``` issue I now understand, this only works if the file is loaded from a file, which is not the case in a notebook. In a notebook it returns "", which means the tmp directory is created in the current working directory.

2. I've added a slightly edited version of Eric's notebook to the master version of Stan.jl. The notebook should become visible after Pkg.checkout("Stan"). 

3. Note that if you run a notebook from within the Stan.jl directory, Pkg.update() will in the future skip updating Stan.jl. A better approach is to copy the notebook to a different location and then start/run iJulia.

4. If someone figures out why I can't remove a tmp dir in Windows (or what run command I should use), that would be appreciated.

**Comment by chameroy** [comment]
I've done two things:
I copied bernoulli.jl from the location of the Stan package to my desktop. Ran it using the command line - no errors.
I also created a file, stan_example.jl that used the example code from the Stan.jl documentation. I could also get that to execute using the command line, but only after commenting out the "sim1 =" line.
[bernoulli.jl.txt](https://github.com/goedman/Stan.jl/files/1221019/bernoulli.jl.txt)
[stan_example.jl.txt](https://github.com/goedman/Stan.jl/files/1221020/stan_example.jl.txt)

So, will this issue cause problems for me if I continue working on Windows? Is there a work around?

Eric

**Comment by goedman** [comment]
Hi Eric,

I don’t think you will run into problems.

The “sim1 = ...” is not working because it should read “rc, sim1 = ...”, exactly as in the line above the if statement in your script. But that would just run the simulation again, you already have the results in sim1.

Does that clarify things?

**Comment by chameroy** [comment]
So what's happening is that the first call to stan() is returning a tuple. The second call is trying to overwrite the tuple created by the first call, creating the error. Correct?

Thank you for all of your help Rob. I really appreciate it.

Eric

**Comment by goedman** [comment]
After the first call, rc is getting the 1st entry of the Tuple that stan() returns. This is a return code which I set in stan() to differentiate what can go wrong. The 2nd component of the Tuple returned by stan() contains the simulated values (converted to a Mamba.Chains object). This is assigned to sim1. Thus sim1, a Mamba.Chains object, can be used to filter a subset of all sampled parameters and the script assigns those to sim.

If the left hand side only is sim1, sim1 ends up as a Tuple and can’t be used directly to filter a subset and this was the error Julia reported.

**Comment by chameroy** [comment]
Thanks for the explanation.

Again, thanks for your help.

Eric
