### ISSUE TITLE
mambaThinning vs. CmdStan thinning

### ISSUE THREAD

**Issue by goedman** [goedman/Stan.jl#49]
Hi @RalphAS,

Thanks for the patch. Are you using Stan.jl v2.0.0 or master (after `Pkg.checkout("Stan")`?

In the master version, the call to stanmodel() has an additional keyword argument `mambaThinning` which is set to 1 by default. This means by default thinning occurs in CmdStan, but optionally you can not use CmdStan and postpone thinning until later. One place where that might be useful is the CmdStan problem/issue that thinning and attempting to save warmups is not working correctly. See also http://goedman.github.io/Stan.jl/latest/VERSIONS.html#Version-2.0.0-1 .

I apologies for not having updated METADATA yet, but this is because I am at the tail end of a rather complicated move ( https://github.com/goedman/Stan.jl/issues/46 ). I will spend some time on cleaning this up over the next 2 weeks.

Hope it is ok I respond in an issue, not directly on the PR.

Best,
Rob

**Comment by goedman** [comment]
Oops, the 1st link should have been: http://goedman.github.io/Stan.jl/latest/index.html#stanmodel()-1

**Comment by RalphAS** [comment]
I'm using the current master.  Yes, I noticed `mambaThinning`. I think that's a good option to keep separate from the CmdStan logic, for flexibility in post-processing.

**Comment by goedman** [comment]
Thus, will this suffice for you? If so, we can close the PR.

Thinking about Stan.jl v3.x.x the intention is to completely separate the CmdStan usage/interface functionality and the Mamba based parts currently in Stan.jl. In the Stan.jl v3.x.x timeframe I plan to have 2 (or 3) packages to provide all current facilities, but make each package simpler compared to the rather intermingled setup in Stan.jl today. The 3rd package would attempt to decouple plotting facilities (or add Plots.jl as an alternative), but that's a lower priority right now.

**Comment by goedman** [comment]
Merged the proposed patch. Stan thinning was executed twice.
